name: nova_ui_library_example
description: "Demonstrates how to use the nova_ui_library plugin."

publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  nova_ui_library:
    path: ../
  cupertino_icons: ^1.0.8
  widgetbook: ^3.12.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
