name: nova_ui_library
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: 5.10.0
  build_runner: 2.4.15

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

  assets:
    - assets/icons/icons_24x24/
    - assets/design-tokens.json

flutter_gen:
  output: lib/src/gen
  line_length: 80
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
