name: nova_ui_library
description: A new Flutter package project.
version: 0.0.1
homepage: "https://github.com/plateron/nova_ui_library"

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.17
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: 5.10.0
  build_runner: ^2.4.8
  widgetbook_generator: ^3.7.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
  uses-material-design: true
  assets:
    - assets/design-tokens.json
    - assets/icons/specialized_icons/
    - assets/icons/svg/

flutter_gen:
  output: lib/src/gen
  line_length: 80
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
